version: "3.2"

services:
  api:
    build: 
      context: .
      dockerfile: ./infra/node/Dockerfile
    volumes:
    # https://stackoverflow.com/a/32785014/232619
      - ./src:/app
      - /app/node_modules
    command: /usr/local/wait-for-it.sh postgres:5432 -- npm run dev
    env_file: 
      - infra/node/api.env
    ports:
      - 3000:80
    depends_on:
      - postgres
  postgres:
    build: 
      context: .
      dockerfile: ./infra/postgres/Dockerfile
    # command: -c ssl=on
    restart: on-failure
    env_file:
      - infra/postgres/db.env
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
