version: "3.2"

services:
  api:
    build: .
    volumes:
      - .:/app
    command: npm run dev
    env_file: 
      - web.env
    ports:
      - 3000:80
    depends_on:
      - db
  db:
    build: ./postgres
    # command: -c ssl=on
    restart: on-failure
    env_file:
      - postgres/db.env
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
