version: "3.2"

services:
  api:
    build: .
    volumes:
      - .:/app
    command: npm run dev
    env_file: 
      - web.env
    ports:
      - 3000:80
    depends_on:
      - db
  db:
    image: postgres:10.5-alpine
    restart: always
    env_file:
      - db.env
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
