version: "3.2"

services:
  api:
    build: ./infra/node
    volumes:
      - .:/app
    command: npm run dev
    env_file: 
      - infra/node/api.env
    ports:
      - 3000:80
    depends_on:
      - db
  db:
    build: ./infra/postgres
    # command: -c ssl=on
    restart: on-failure
    env_file:
      - infra/postgres/db.env
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
